#include "nlohmann/json.hpp"
#include <iostream>

#define EXPAND_STR(VERSION_NUMBER) #VERSION_NUMBER
#define STR(VERSION_NUMBER) EXPAND_STR(VERSION_NUMBER)

int main() {
	std::cout <<
		STR(NLOHMANN_JSON_VERSION_MAJOR) "."
		STR(NLOHMANN_JSON_VERSION_MINOR) "."
		STR(NLOHMANN_JSON_VERSION_PATCH);
}
